//- 英文/繁中自動檢測翻譯
(function () {
  const translations = {
    'en': { // 英文/預設
      answer: 'Answer',
      data_source: 'Data source',
      does_it_helpful: 'Do you think this article is helpful?',
      helpful: 'Helpful',
      unhelpful: 'Unhelpful',
      feedback: 'Feedback',
      cancel: 'Cancel',
      submit: 'Submit',
      share: 'Share',
      read_more: 'People also ask',
      aigc_policy: 'The content on this page is generated by an AI language model that consolidates information from the Stock Knowledge Base website and does not represent the official stance. Please exercise caution when adopting or citing the content.',
      loading: 'Loading'
    },
    'zh-tw': { // 中文
      answer: '回答',
      data_source: '資料來源',
      does_it_helpful: '你覺得這篇文章有幫助嗎？',
      helpful: '有幫助',
      unhelpful: '沒幫助',
      feedback: '問題回報',
      cancel: '取消',
      submit: '送出',
      share: '分享給好友',
      read_more: '還想知道什麼？',
      aigc_policy: '本頁面內容由 AI 大語言模型彙整股股知識庫網站資料產出，不代表股股及 Mlytics 官方立場。請謹慎採納及引用內容。',
      loading: '載入中'
    },
    'ms': { // 馬來文
      answer: 'Jawapan',
      data_source: 'Sumber data',
      does_it_helpful: 'Adakah anda rasa artikel ini berguna?',
      helpful: 'Berguna',
      unhelpful: 'Tidak Berguna',
      feedback: 'Maklum Balas',
      cancel: 'Batal',
      submit: 'Hantar',
      share: 'Kongsi',
      read_more: 'Orang juga bertanya',
      aigc_policy: 'Halaman ini dihasilkan oleh AI dan tidak mewakili pendirian rasmi syarikat.',
      loading: 'Memuatkan'
    },
     'th': { // 泰文
      answer: 'คำตอบ',
      data_source: 'แหล่งข้อมูล',
      does_it_helpful: 'คุณคิดว่าเนื้อหานี้มีประโยชน์หรือไม่?',
      helpful: 'มีประโยชน์',
      unhelpful: 'ไม่เป็นประโยชน์',
      feedback: 'ข้อเสนอแนะ',
      cancel: 'ยกเลิก',
      submit: 'ส่ง',
      share: 'แชร์',
      read_more: 'คำแนะนำการอ่านที่สร้างโดย AI',
      aigc_policy: 'คนอื่นก็ถามเช่นกัน',
      loading: 'กำลังโหลด'
    },
    'vi': { // 越南文
      answer: 'Trả lời',
      data_source: 'Nguồn dữ liệu',
      does_it_helpful: 'Bạn có nghĩ bài viết này hữu ích không?',
      helpful: 'Hữu ích',
      unhelpful: 'Không hữu ích',
      feedback: 'Phản hồi',
      cancel: 'Hủy bỏ',
      submit: 'Gửi',
      share: 'Chia sẻ',
      read_more: 'Mọi người cũng hỏi',
      aigc_policy: 'Trang này được tạo ra bởi AI và không đại diện cho lập trường chính thức của công ty.',
      loading: 'Đang tải'
    },
    'ja': { // 日文
      answer: '回答',
      data_source: 'データソース',
      does_it_helpful: 'この記事は役に立ちましたか？',
      helpful: '役に立つ',
      unhelpful: '役に立たない',
      feedback: 'フィードバック',
      cancel: 'キャンセル',
      submit: '送信',
      share: 'シェア',
      read_more: '他の人も尋ねること',
      aigc_policy: 'このページはAIによって生成されており、会社の公式見解を代表するものではありません。',
      loading: '読み込み中'
    },
    'ko': { // 韓文
      answer: '답변',
      data_source: '데이터 출처',
      does_it_helpful: '이 기사가 도움이 되셨나요?',
      helpful: '도움이 됨',
      unhelpful: '도움이 안 됨',
      feedback: '피드백',
      cancel: '취소',
      submit: '제출',
      share: '공유',
      read_more: '사람들이 또한 묻습니',
      aigc_policy: '이 페이지는 AI에 의해 생성되었으며 회사의 공식 입장을 대표하지 않습니다.',
      loading: '로딩 중'
    }
  };
  const userLang = navigator.language || navigator.userLanguage;
  const lang = userLang.toLowerCase();
  const selectedLang = translations[lang] ? lang : 'en';
  document.querySelectorAll('[data-i18n-key]').forEach(elem => {
    const key = elem.getAttribute('data-i18n-key');
    const translatedText = translations[selectedLang][key];
    if (translatedText) {
      elem.textContent = translatedText;
    }
  });
})();

